replicaCount: 1

image:
  repository: botpress/server
  tag: latest
  pullPolicy: IfNotPresent

env:
  BPFS_STORAGE: database
  EXTERNAL_URL: https://botpress.seudominio.com.br
  BP_PRODUCTION: true

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

persistence:
  enabled: true
  storageClass: longhorn
  accessModes:
    - ReadWriteOnce
  size: 5Gi

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: botpress.seudominio.com.br
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: botpress-tls
      hosts:
        - botpress.seudominio.com.br

postgresql:
  auth:
    username: botpress
    password: senha1234
    database: botpress
  primary:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: "longhorn"